/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_FINALSERVER_H_
#define JSONRPC_CPP_STUB_FINALSERVER_H_

#include <iostream>
#include <jsonrpccpp/server.h>
#include <jsonrpccpp/server/connectors/httpserver.h>
#include <stdio.h>
#include <string>

class finalServer : public jsonrpc::AbstractServer<finalServer>
{
    public:

        
        finalServer(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<finalServer>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("move", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "action",jsonrpc::JSON_STRING,"class_id",jsonrpc::JSON_STRING,"json_object",jsonrpc::JSON_OBJECT,"location",jsonrpc::JSON_OBJECT,"object_id",jsonrpc::JSON_STRING, NULL), &finalServer::moveI);
            this->bindAndAddMethod(jsonrpc::Procedure("complete", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &finalServer::completeI);
        }

        inline virtual void moveI(const Json::Value &request, Json::Value &response)
        {
            response = this->move(request["action"].asString(), request["class_id"].asString(), request["json_object"], request["location"], request["object_id"].asString());
        }
        inline virtual void completeI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->complete();
        }
        virtual Json::Value move(const std::string& action, const std::string& class_id, const Json::Value& json_object, const Json::Value& location, const std::string& object_id) = 0;
        virtual Json::Value complete() = 0;
        static std::map<std::string, Motorcycle *> Motorcycle_Map;
};

#endif //JSONRPC_CPP_STUB_FINALSERVER_H_
